all:
	make -C cube
	make -C physics
#	make -C pong
#	make -C gui
#	make -C particle

clean:
	make -C cube clean
	make -C physics clean
#	make -C pong clean
#	make -C gui clean
#	make -C particle clean

