all:
	make -C cube
	make -C easter_bunny
	make -C walk
	make -C human
	make -C pong
	make -C gui
	make -C particle

clean:
	make -C cube clean
	make -C easter_bunny clean
	make -C walk clean
	make -C human clean
	make -C pong clean
	make -C gui clean
	make -C particle clean

