SRCS = $(shell find -name '*.cpp')
OBJS = $(addsuffix .o,$(basename $(SRCS)))

INCLUDE = -I/usr/include/ -I../include
LIBDIR  = -L/usr/X11R6/lib 

CC = gcc
CFLAGS = -Wall $(INCLUDE)

all: $(OBJS) lib

%.o : %.cpp
	$(CC) $(CFLAGS) -c -o $@ $<

lib: $(OBJS)
	ar -rcs oxygarum.a $^

clean:
	rm $(OBJS)
	rm oxygarum.a

