SRCS = $(shell find -name '*.cpp')
OBJS = $(addsuffix .o,$(basename $(SRCS)))

INCLUDE = -I/usr/include/ -I../include
LIBDIR  = -L/usr/X11R6/lib 

CC = g++
CFLAGS = -Wall $(INCLUDE)
STYLEFLAGS = --style=allman --indent-classes --indent-switches

all: $(OBJS) lib

%.o : %.cpp
	$(CC) $(CFLAGS) -c -o $@ $<

lib: $(OBJS)
	ar -rcs oxygarum.a $^

style: $(SRCS)
	astyle $(STYLEFLAGS) $^

clean:
	rm $(OBJS)
	rm oxygarum.a

